import pandas as pd

# List of names extracted from the images
names = [
    "Timothy Crump",
    "Ahmed, Neraj (Unverified)",
    "Aidan Bugler (Unverified)",
    "Alex Barnes (External)",
    "Alfie Fox-Heaton",
    "Andy Giles (External)",
    "Ball, Andrew (M4) (External)",
    "Basak Bengi Macit (Unverified)",
    "Beech, Chris (London) (External)",
    "Ben Robinson (Unverified)",
    "Bowes, Mark (Unverified)",
    "Chris Burn (External)",
    "Chris Wright (Unverified)",
    "Christopher McCartney (External)",
    "Cornelia Waymouth (External)",
    "COTTON Jessica (ENGIE... (External)",
    "Dan Hisgett (Unverified)",
    "Dave Whiting (External)",
    "David Goodall (External)",
    "Debbie Mitchell (External)",
    "Devenny, Gail (Unverified)",
    "Dharmesh Jadavji (External)",
    "Ebike (Unverified)",
    "Ewan Morgan (Unverified)",
    "Farrar, Joanne (External)",
    "Fatima Sow (External)",
    "Fireflies.ai Notetaker ... (Unverified)",
    "Garrett, Jamie (Unverified)",
    "Garry McLoughlin (External)",
    "Grace Viney (Unverified)",
    "Green, Julian (External)",
    "Grout, Nicola C (Unverified)",
    "haigh, Ashley (External)",
    "Hannay-Wilson, Guy (Unverified)",
    "Harkin, Luke (Generation and Tra...",
    "Hassan, Ahmed (Unverified)",
    "Hicks, Raymond Gordon (External)",
    "Isabelle Anstey [NESO] (External)",
    "James Harries (Unverified)",
    "James Porter (Unverified)",
    "Jasmine Anionwu (Unverified)",
    "Jon (Unverified)",
    "Julie Cox (External)",
    "Keil, Joerg (External)",
    "Kieran McGoldrick (Unverified)",
    "Kirsty Appleby (Unverified)",
    "Kirsty Brewer (External)",
    "Kris Jacob (Unverified)",
    "Laura Loughran (Unverified)",
    "Lauren Rowe (External)",
    "Malcolm Mudimu (Unverified)",
    "Mari (Unverified)",
    "Mark Hewett (External)",
    "Marwa Addouz (Unverified)",
    "Matthew Atkinson (External)",
    "Matthew C Smith (External)",
    "Matthew Daws (External)",
    "Matthew Williams (Unverified)",
    "McGlynn, Dara (Generation and T...",
    "Melvyn Wilson (External)",
    "Michaelis, Sandra (Unverified)",
    "Mike Stafford (External)",
    "Nick Cannon - CBM (Unverified)",
    "Nicole Jackson (Unverified)",
    "Paul Booley (Unverified)",
    "Paul Johnstone (External)",
    "Paul O'Connor (External)",
    "Paul Sullivan (Unverified)",
    "Peskova, Lenka (Generation and T...",
    "Pete Hughes (External)",
    "Phil Hobbins (Unverified)",
    "Piper, Jack (Energy Secu... (External)",
    "PRASHER Varun (Unverified)",
    "Rachel Priestley [NESO] (External)",
    "Rhiannon McEvoy (External)",
    "Richard Nash (Unverified)",
    "Richards, Isabella (Unverified)",
    "Ross Edwards (External)",
    "Seaton, Rob (Energy Se... (External)",
    "Shrigley Anna (Unverified)",
    "Stephen O'Hare (External)",
    "Steve Frost (G4S) (Unverified)",
    "Steven Puetz (External)",
    "Sylvia Bunting (GB) (Unverified)",
    "Thomas McCartney (External)"
]

# Create a DataFrame
df = pd.DataFrame(names, columns=['Name'])

# Save to Excel
output_file = 'meeting_attendees.xlsx'
df.to_excel(output_file, index=False, sheet_name='Attendees')

print(f"Excel file created successfully: {output_file}")
print(f"Total number of attendees: {len(names)}")
